name: Commit

on:
  pull_request:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
      - uses: snow-actions/git-config-user@v1.0.0
      - run: echo "test" >> test
      - run: |
          git add .
          git commit -m "test"
          git push
